name: GitHub Actions example using GameCI

on:
  workflow_dispatch:

jobs:
  build:
    name: Build my project
    runs-on: self-hosted
    steps:
      - name: Starting
        run: echo 'Starting...'

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # Test
#       - name: Run tests
#         uses: game-ci/unity-test-runner@v2
#         env:
#           UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
#         with:
#           projectPath: TheMostAwesomeGameEverMade
#           githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}        
        with:
          projectPath: TheMostAwesomeGameEverMade
          targetPlatform: WebGL

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: TheMostAwesomeGameEverMade/build